ALTER TABLE `PREFIX_gsr_rating` ADD `RTG_LANG_ID` TINYINT UNSIGNED NOT NULL DEFAULT '0' AFTER `RTG_PROD_ID`;
ALTER TABLE `PREFIX_gsr_review` ADD `RVW_LANG_ID` TINYINT UNSIGNED NOT NULL DEFAULT '0' AFTER `RVW_PROD_ID`;
ALTER TABLE `PREFIX_gsr_review` MODIFY `RVW_DATE_ADD` timestamp NULL AFTER `RVW_LANG_ID`;
ALTER TABLE `PREFIX_gsr_review` MODIFY `RVW_DATE_UPD` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `RVW_DATE_ADD`;
CREATE TABLE IF NOT EXISTS `PREFIX_gsr_review_report` (`RPT_RVW_ID` INT UNSIGNED NOT NULL DEFAULT '0', `RPT_CUST_ID` INT UNSIGNED NOT NULL, PRIMARY KEY (`RPT_RVW_ID`,`RPT_CUST_ID`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;